name: "South Lanarkshire Bin Collection"
description: "Tracks bin collections days"
version: "0.0.6"
slug: "south-lanarkshire-bin-collections"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  refresh_interval: hourly
schema:
  refresh_interval: list(15min|hourly|daily)