name: "South Lanarkshire Bin Collection"
description: "Tracks bin collections days"
version: "0.0.5"
slug: "south-lanarkshire-bin-collections"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  refresh_interval_seconds: 3600
schema:
  refresh_interval_seconds: int